import { AiOutlineLink as Link } from 'react-icons/ai';
import { FaNewspaper as Newspaper } from 'react-icons/fa';
import { GiDinosaurRex as Dino } from 'react-icons/gi';
import { HiOutlineChevronDoubleRight as Expand } from 'react-icons/hi';
import {
    MdChevronLeft as ArrowLeft,
    MdChevronRight as ArrowRight,
    MdContentCopy as Copy,
    MdDarkMode as DarkMode,
    MdInfoOutline as Info,
    MdLabelOutline as Label,
    MdLightMode as LightMode,
    MdLockOutline as Privacy,
    MdMail as Mail,
    MdOpenInFull as Open,
    MdOutlineArchive as Archive,
    MdOutlineColorLens as Colors,
    MdOutlineHelpOutline as Support,
    MdOutlineLogout as Logout,
    MdOutlinePeopleAlt as People,
    MdOutlinePushPin as Pin,
    MdOutlineSecurity as Security,
    MdPhone as Phone,
    MdSettings as Settings,
    MdSmartphone as Smartphone,
    MdStarBorder as Star,
    MdOutlineClose as Close,
} from 'react-icons/md';
import {
    FiArrowUpLeft as ArrowUpLeft,
    FiArrowUpRight as ArrowUpRight,
    FiBell as Bell,
    FiMenu as Menu,
    FiSearch as Search,
    FiTrash as Trash,
} from 'react-icons/fi';
import {
    RiComputerLine as Interface,
    RiMoneyDollarCircleLine as Money,
    RiStickyNoteFill as Note,
    RiUserLine as User,
} from 'react-icons/ri';
import {
    BsThreeDotsVertical as DotsMenu,
    BsFillGridFill as Grid,
    BsPlusLg as Plus,
    BsFillHddStackFill as Stack,
} from 'react-icons/bs';

export const Icons = {
    Note,
    Plus,
    Stack,
    Link,
    Trash,
    Money,
    Close,
    DotsMenu,
    Menu,
    Label,
    Search,
    Star,
    People,
    Settings,
    Newspaper,
    DarkMode,
    LightMode,
    Grid,
    Dino,
    Archive,
    Colors,
    Open,
    Pin,
    Copy,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    ArrowUpLeft,
    Security,
    Privacy,
    User,
    Interface,
    Info,
    Smartphone,
    Mail,
    Phone,
    Bell,
    Support,
    Logout,
    Expand,
};
