import {
    MdOutlineArchive as Archive,
    MdChevronLeft as ArrowLeft,
    MdChevronRight as ArrowRight,
    MdOutlineColorLens as Colors,
    MdContentCopy as Copy,
    MdDarkMode as DarkMode,
    MdInfoOutline as Info,
    MdLabelOutline as Label,
    MdLightMode as LightMode,
    MdMail as Mail,
    MdOpenInFull as Open,
    MdOutlinePeopleAlt as People,
    MdPhone as Phone,
    MdOutlinePushPin as Pin,
    MdLockOutline as Privacy,
    MdOutlineSecurity as Security,
    MdSettings as Settings,
    MdSmartphone as Smartphone,
    MdStarBorder as Star,
} from 'react-icons/md';
import {
    FiArrowUpLeft as ArrowUpLeft,
    FiArrowUpRight as ArrowUpRight,
    FiBell as Bell,
    FiMenu as Menu,
    FiSearch as Search,
    FiTrash as Trash,
} from 'react-icons/fi';
import {
    RiCloseFill as Close,
    RiComputerLine as Interface,
    RiMoneyDollarCircleLine as Money,
    RiStickyNoteFill as Note,
    RiUserLine as User,
} from 'react-icons/ri';
import {
    BsThreeDotsVertical as DotsMenu,
    BsFillGridFill as Grid,
    BsPlusLg as Plus,
    BsFillHddStackFill as Stack,
} from 'react-icons/bs';

import { GiDinosaurRex as Dino } from 'react-icons/gi';
import { AiOutlineLink as Link } from 'react-icons/ai';
import { FaNewspaper as Newspaper } from 'react-icons/fa';

export const Icons = {
    Note,
    Plus,
    Stack,
    Link,
    Trash,
    Money,
    Close,
    DotsMenu,
    Menu,
    Label,
    Search,
    Star,
    People,
    Settings,
    Newspaper,
    DarkMode,
    LightMode,
    Grid,
    Dino,
    Archive,
    Colors,
    Open,
    Pin,
    Copy,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    ArrowUpLeft,
    Security,
    Privacy,
    User,
    Interface,
    Info,
    Smartphone,
    Mail,
    Phone,
    Bell,
};
